import { AppShell, PageHeader } from "@/components/app-shell";
import { getProviderTopology } from "@/lib/mail-provider";
import { recoveryConfigured } from "@/lib/recovery-envelope";

export const metadata = { title: "Configuración" };
export default function SettingsPage() {
  const topology = getProviderTopology();
  const recoveryReady = recoveryConfigured();

  return <AppShell active="Configuración"><PageHeader eyebrow="Infrastructure" title="Configuración" description="Estado operativo y dependencias de LVL Mail antes de activar infraestructura real." />
    <section className="settings-grid">
      <article className="panel"><span className="eyebrow">DOMINIO</span><h2>mail.lvltechmx.com</h2><p>Un solo subdominio de envío para las aplicaciones conectadas. La reputación se protege por aplicación mediante tracking, cuotas, circuit breaker y guardias de deliverability.</p><div className="setting-status"><span className="status-dot amber"/>Requiere verificación DNS externa</div></article>
      <article className="panel"><span className="eyebrow">PROVIDER LAYER</span><h2>Proveedor desacoplado</h2><p>Las aplicaciones solo consumen <code>/api/v1/send</code>. LVL Mail mantiene slots primario/secundario detrás del mismo contrato y no realiza failover automático cuando el resultado del proveedor es ambiguo.</p><div className="code-stack"><code>Primary: {topology.primary} · {topology.primaryReady ? "ready" : "pending"}</code><code>Secondary: {topology.secondary ?? "not configured"} · {topology.secondaryReady ? "ready" : "pending"}</code><code>Failover: {topology.failoverMode}</code></div><div className="setting-status success-note"><span className="status-dot"/>Contrato independiente del proveedor</div></article>
      <article className="panel"><span className="eyebrow">SEARCH & RECOVERY</span><h2>Recovery envelopes cifrados</h2><p>Solo las plantillas no críticas aprobadas guardan temporalmente un payload cifrado AES-256-GCM. OTP, confirmación y recuperación de contraseña nunca usan replay.</p><div className="code-stack"><code>LVL_MAIL_RECOVERY_KEY</code><code>transactional-notice · 24 h</code><code>notification · 72 h</code></div><div className={recoveryReady ? "setting-status success-note" : "setting-status"}><span className={recoveryReady ? "status-dot" : "status-dot amber"}/>{recoveryReady ? "Recovery encryption configurada" : "Recovery encryption pendiente"}</div></article>
      <article className="panel"><span className="eyebrow">SECRETS</span><h2>Variables del servidor</h2><div className="code-stack"><code>LVL_MAIL_PRIMARY_PROVIDER</code><code>LVL_MAIL_SECONDARY_PROVIDER</code><code>LVL_MAIL_FAILOVER_MODE</code><code>RESEND_API_KEY</code><code>RESEND_WEBHOOK_SECRET</code><code>LVL_MAIL_SENDING_DOMAIN</code><code>SUPABASE_URL</code><code>SUPABASE_SERVICE_ROLE_KEY</code><code>LVL_MAIL_RECOVERY_KEY</code><code>LVL_MAIL_ADMIN_USER</code><code>LVL_MAIL_ADMIN_PASSWORD</code><code>LVL_MAIL_CRON_SECRET</code></div><p>Son secretos o configuración de servidor. Ninguno debe usar el prefijo <code>NEXT_PUBLIC_</code>.</p></article>
      <article className="panel"><span className="eyebrow">CONTROL PLANE</span><h2>Políticas por aplicación</h2><p>Cada web puede operar en Live, Test o Pausada, con límites por minuto/día, reserva P0, plantillas habilitadas, circuit breaker y guardia automática de reputación.</p><div className="setting-status success-note"><span className="status-dot"/>Aislamiento por aplicación</div></article>
      <article className="panel"><span className="eyebrow">OPERATIONS & RELIABILITY</span><h2>SLOs + incident engine</h2><p>LVL Mail mide aceptación y entrega P0, latencia P50/P95/P99, rechazos, bounces y complaints. Las condiciones abren incidentes por aplicación y se recuperan sin afectar la trazabilidad histórica.</p><div className="code-stack"><code>POST /api/internal/reliability/sweep</code><code>Authorization: Bearer LVL_MAIL_CRON_SECRET</code></div><div className="setting-status success-note"><span className="status-dot"/>Preparado para evaluación periódica</div></article>
      <article className="panel"><span className="eyebrow">WEBHOOK</span><h2>/api/webhooks/resend</h2><p>Verifica firma Svix usando el cuerpo crudo, deduplica por <code>svix-id</code>, reconcilia cada evento con su tracking ID, reevalúa reputación/reliability y elimina recovery payloads cuando un correo llega a un estado terminal no replayable.</p><div className="setting-status success-note"><span className="status-dot"/>Tracking obligatorio</div></article>
      <article className="panel"><span className="eyebrow">SEGURIDAD</span><h2>Consola administrativa</h2><p>La UI falla cerrada en producción. Las acciones administrativas sensibles usan autenticación independiente, rotación de claves, búsqueda privada y auditoría append-only.</p><div className="setting-status success-note"><span className="status-dot"/>Fail-closed + audit log</div></article>
      <article className="panel"><span className="eyebrow">PERSISTENCIA</span><h2>Supabase</h2><p>Las extensiones enterprise se mantienen como SQL revisable hasta seleccionar el proyecto dedicado. Las funciones nuevas usan <code>security invoker</code>, RLS y permisos explícitos al <code>service_role</code>.</p></article>
      <article className="panel"><span className="eyebrow">ENVÍO</span><h2>/api/v1/send</h2><p>El pipeline es: autenticación → tracking → plantilla → reputación → cuota/circuit breaker → supresión → recovery envelope opcional → provider adapter → reconciliación por webhook.</p></article>
    </section>
  </AppShell>;
}
