import { AppShell, PageHeader } from "@/components/app-shell";

export const metadata = { title: "Configuración" };
export default function SettingsPage() {
  return <AppShell active="Configuración"><PageHeader eyebrow="Infrastructure" title="Configuración" description="Estado operativo y dependencias de LVL Mail antes de activar infraestructura real." />
    <section className="settings-grid">
      <article className="panel"><span className="eyebrow">DOMINIO</span><h2>mail.lvltechmx.com</h2><p>Un solo subdominio de envío para las aplicaciones conectadas. La reputación se protege por aplicación mediante tracking, cuotas, circuit breaker y guardias de deliverability.</p><div className="setting-status"><span className="status-dot amber"/>Requiere verificación DNS externa</div></article>
      <article className="panel"><span className="eyebrow">PROVIDER LAYER</span><h2>Proveedor desacoplado</h2><p>Las aplicaciones solo consumen <code>/api/v1/send</code>. El adaptador seleccionado por <code>LVL_MAIL_PROVIDER</code> es el único componente que conoce al proveedor de entrega.</p><div className="code-stack"><code>LVL_MAIL_PROVIDER=resend</code><code>RESEND_API_KEY</code><code>RESEND_WEBHOOK_SECRET</code></div><div className="setting-status success-note"><span className="status-dot"/>Contrato de envío independiente del proveedor</div></article>
      <article className="panel"><span className="eyebrow">SECRETS</span><h2>Variables del servidor</h2><div className="code-stack"><code>LVL_MAIL_PROVIDER</code><code>RESEND_API_KEY</code><code>RESEND_WEBHOOK_SECRET</code><code>LVL_MAIL_SENDING_DOMAIN</code><code>SUPABASE_URL</code><code>SUPABASE_SERVICE_ROLE_KEY</code><code>LVL_MAIL_ADMIN_USER</code><code>LVL_MAIL_ADMIN_PASSWORD</code><code>LVL_MAIL_CRON_SECRET</code></div><p>Son secretos o configuración de servidor. Ninguno debe usar el prefijo <code>NEXT_PUBLIC_</code>.</p></article>
      <article className="panel"><span className="eyebrow">CONTROL PLANE</span><h2>Políticas por aplicación</h2><p>Cada web puede operar en Live, Test o Pausada, con límites por minuto/día, reserva P0, plantillas habilitadas, circuit breaker y guardia automática de reputación.</p><div className="setting-status success-note"><span className="status-dot"/>Aislamiento por aplicación</div></article>
      <article className="panel"><span className="eyebrow">OPERATIONS & RELIABILITY</span><h2>SLOs + incident engine</h2><p>LVL Mail mide aceptación y entrega P0, latencia P50/P95/P99, rechazos, bounces y complaints. Las condiciones abren incidentes por aplicación y se recuperan sin afectar la trazabilidad histórica.</p><div className="code-stack"><code>POST /api/internal/reliability/sweep</code><code>Authorization: Bearer LVL_MAIL_CRON_SECRET</code></div><div className="setting-status success-note"><span className="status-dot"/>Preparado para evaluación periódica</div></article>
      <article className="panel"><span className="eyebrow">WEBHOOK</span><h2>/api/webhooks/resend</h2><p>Verifica firma Svix usando el cuerpo crudo, deduplica por <code>svix-id</code>, reconcilia cada evento con su tracking ID y reevalúa reputación + reliability por aplicación.</p><div className="setting-status success-note"><span className="status-dot"/>Tracking obligatorio</div></article>
      <article className="panel"><span className="eyebrow">SEGURIDAD</span><h2>Consola administrativa</h2><p>La UI falla cerrada en producción. Las acciones administrativas sensibles usan autenticación independiente, rotación de claves y auditoría append-only.</p><div className="setting-status success-note"><span className="status-dot"/>Fail-closed + audit log</div></article>
      <article className="panel"><span className="eyebrow">PERSISTENCIA</span><h2>Supabase</h2><p>Las extensiones enterprise se mantienen como SQL revisable hasta seleccionar el proyecto dedicado. Las funciones nuevas usan <code>security invoker</code>, RLS y permisos explícitos al <code>service_role</code>.</p></article>
      <article className="panel"><span className="eyebrow">ENVÍO</span><h2>/api/v1/send</h2><p>El pipeline es: autenticación → tracking → plantilla → reputación → cuota/circuit breaker → supresión → provider adapter → reconciliación por webhook.</p></article>
    </section>
  </AppShell>;
}
